apiVersion: k3d.io/v1alpha4 # this will change in the future as we make everything more stable
kind: Simple 
metadata:
  name: ${CLUSTER_NAME}
servers: 1
agents: 1
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  host: ${CLUSTER_NAME}.${LOCAL_DEV_DNS_SUFFIX} # important for the `server` setting in the kubeconfig
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
  hostPort: "6445" # where the Kubernetes API listening port will be mapped to on your host system

volumes:
  - volume: ${K3D_VOLUMES_OVERRIDE}:/var/lib/rancher/k3s/storage
    nodeFilters:
      - all
ports: # same as `--port '80:80@loadbalancer'`
  - port: 0.0.0.0:80:80 
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:443:443
    nodeFilters:
      - loadbalancer
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.<CLUSTER_NAME>.<LOCAL_DEV_DNS_SUFFIX>`
    name: registry.${CLUSTER_NAME}.${LOCAL_DEV_DNS_SUFFIX}
    host: "0.0.0.0"
    hostPort: "5000"
options:
  k3d: # k3d runtime settings
    wait: true
    timeout: 300s
    
