apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
    processors:

    exporters:
      logging: 
      # prometheus:
      #   endpoint: "1.2.3.4:1234"
      #   tls:
      #     ca_file: "/path/to/ca.pem"
      #     cert_file: "/path/to/cert.pem"
      #     key_file: "/path/to/key.pem"
      #   namespace: test-space
      #   const_labels:
      #     label1: value1
      #     "another label": spaced value
      #   send_timestamps: true
      #   metric_expiration: 180m
      #   enable_open_metrics: true
      #   resource_to_telemetry_conversion:
      #     enabled: true

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]
