apiVersion: v1
kind: Namespace
metadata:
  name: testapp2
  annotations:
    owner: argocd
    app: testapp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp2
  name: testapp2
  namespace: testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  strategy: {}
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - image: nginx:latest
        name: testapp2
        resources: {}