apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: opentelemetry-collector-instrumentation
  namespace: argocd
spec:
  destination:
    namespace: opentelemetry
    server: https://kubernetes.default.svc
  project: base-services
  source:
    path: base-services/opentelemetry-operator/collector-instrumentation
    repoURL: https://github.com/lukeab/fakerepo.git
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
