apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
  namespace: opentelemetry-operator
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      logging:
      prometheusremotewrite:
        endpoint: "http://prom-operator-kube-prometh-prometheus.prometheus.svc.cluster.local:9090/api/v1/write"
        namespace: prometheus
        resource_to_telemetry_conversion:
          enabled: true
        external_labels:
          server: opentelemetry
      otlp:
        endpoint: tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp]
        metrics: 
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [logging, prometheusremotewrite]

