apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-services
  namespace: base-services
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for local environment base services to be deployed through
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # clusterResourceWhitelist:
  # - group: '*'
  #   kind: '*'
  # sourceRepos:
  # - '*'
  