apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  destination:
    namespace: testapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: testapp
    repoURL: https://github.com/lukeab/k8s-local-dev-env-argocd.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  