configs:
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "ca-local-dev"
    hosts: 
      - argocd.local-dev.local.gd
    tls: 
      - secretName: argocd-tls
        hosts:
          - argocd.local-dev.local.gd