apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec: 
    description: "Root project for all other projects in the deployment"
    
    # Allow manifests to deploy from any Git repos
    sourceRepos:
    - '*'